/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controle.AsignacionControlador;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Modelo.Usuarios;

public class ControlesAsignacion extends javax.swing.JFrame {

    // Instancia del controlador
    AsignacionControlador controlador = new AsignacionControlador();
    private Usuarios usuarioActual;

    // Constructor vacío
    public ControlesAsignacion() {
        initComponents();
        prepararPantalla();
    }

    // Constructor principal que recibe el usuario desde el Menú
    public ControlesAsignacion(Usuarios usuario) {
        this.usuarioActual = usuario;
        initComponents();
        prepararPantalla();
        actualizarTabla();
        aplicarPermisos();
    }

    // Centraliza la configuración visual y de teclado
    private void prepararPantalla() {
        GestorVistas.configurarVentanaBase(this, "Asignación de Viajes - Hirata");
        GestorVistas.configurarAtajosGlobales(this, btnAsignar, false);
        GestorVistas.configurarTabla(tablaAsignaciones);

        // CAMBIO AQUÍ: El controlador usa un solo método para ambos combos
        controlador.cargarCombos(ComboBoxCamion, ComboBoxConductor);
    }

    // 2. Corregir el método de actualización de tabla
    private void actualizarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaAsignaciones.getModel();
        // CAMBIO AQUÍ: El método en el controlador se llama actualizarTabla, no cargarTabla
        controlador.actualizarTabla(modelo);
    }

    public void aplicarPermisos() {
    if (usuarioActual == null) return;
    String rol = usuarioActual.getRol();

    // Si el rol NO es "Admin", bloqueamos todo automáticamente
    if (!rol.equalsIgnoreCase("Admin")) {
        btnAsignar.setEnabled(false);
        ComboBoxCamion.setEnabled(false);
        ComboBoxConductor.setEnabled(false);
    }
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxConductor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxCamion = new javax.swing.JComboBox<>();
        btnAsignar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAsignaciones = new javax.swing.JTable();
        btnReflescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboBoxConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxConductorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        jLabel2.setText("Controlador DE Asignacion");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Conductor:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Camion:");

        ComboBoxCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCamionActionPerformed(evt);
            }
        });

        btnAsignar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tablaAsignaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Conductor", "Patente del Camion"
            }
        ));
        tablaAsignaciones.setPreferredSize(new java.awt.Dimension(600, 400));
        tablaAsignaciones.setRequestFocusEnabled(false);
        tablaAsignaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAsignacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAsignaciones);

        btnReflescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReflescar.setText("Reflescar ");
        btnReflescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReflescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReflescar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnAsignar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnReflescar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btnAsignar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxConductorActionPerformed

    private void ComboBoxCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCamionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCamionActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    GestorVistas.volverAlMenu(this);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tablaAsignacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAsignacionesMouseClicked

    }//GEN-LAST:event_tablaAsignacionesMouseClicked

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
    if (usuarioActual == null) return;

        Object itemCamion = ComboBoxCamion.getSelectedItem();
        Object itemChofer = ComboBoxConductor.getSelectedItem();

        if (itemCamion == null || itemChofer == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un camión y un chofer.");
            return;
        }

        String patente = itemCamion.toString();
        String chofer = itemChofer.toString();

        // Llamada al controlador para guardar la asignación
        boolean exito = controlador.realizarAsignacionSegura(patente, chofer, usuarioActual);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Asignación guardada con éxito.");
            actualizarTabla(); // Refresca la tabla para ver el nuevo registro
        } else {
            JOptionPane.showMessageDialog(this, "Error: El camión ya está ocupado o no tiene permisos.");
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnReflescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReflescarActionPerformed
    actualizarTabla();
    // CAMBIO AQUÍ: Usar el método correcto del controlador
    controlador.cargarCombos(ComboBoxCamion, ComboBoxConductor);
    JOptionPane.showMessageDialog(this, "Datos actualizados.");
    }//GEN-LAST:event_btnReflescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new ControlesAsignacion().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCamion;
    private javax.swing.JComboBox<String> ComboBoxConductor;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnReflescar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAsignaciones;
    // End of variables declaration//GEN-END:variables
}
