/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controle.CamionControlador;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import Modelo.Usuarios;
/**
 *
 * @author tomas
 */
public class ControlesCamiones extends javax.swing.JFrame {

    // 1. Instanciamos el controlador
    CamionControlador controlador = new CamionControlador();

    // Variable global para guardar el usuario que inició sesión
    private Usuarios usuarioActual;

    // Constructor vacío por si lo necesitas
    public ControlesCamiones() {
        initComponents();
        actualizarTabla();
        configurarPlaceholders();
    }
    
    public ControlesCamiones(Usuarios usuario) {
        this.usuarioActual = usuario;
        initComponents();
        actualizarTabla();
        configurarPlaceholders();
        
        // Aplicamos los permisos justo después de cargar la pantalla
        aplicarPermisos(usuario); 
    }
    
    
    
    // --- MÉTODO MAGICO PARA LOS EDIT TEXT ---
    private void configurarPlaceholders() {
        // Metemos todos tus campos en una lista para no repetir codigo
        javax.swing.JTextField[] campos = {
            lblNumeracion, lblMatricula, lblMarca, lblModelo, 
            lblNombreChofer, lblKM
        };

        for (javax.swing.JTextField campo : campos) {
            // Guardamos el nombre original que pusiste en NetBeans como "guia"
            String textoGuia = campo.getText();

            campo.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    // Si el usuario hace clic y está el texto de guia, lo borramos
                    if (campo.getText().equals(textoGuia)) {
                        campo.setText("");
                        campo.setForeground(Color.BLACK); // Color de letra normal al escribir
                    }
                }

                @Override
                public void focusLost(FocusEvent e) {
                    // Si el usuario se sale y no escribió nada, ponemos la guia de nuevo
                    if (campo.getText().isEmpty()) {
                        campo.setForeground(new Color(204, 204, 204)); // Color gris
                        campo.setText(textoGuia);
                    }
                }
            });
        }
    }

    public void aplicarPermisos(Usuarios usuario) {
        if (usuario == null) return;
        String rol = usuario.getRol();

        switch (rol) {
            case "Admin":
                // Acceso total
                break;

            case "Revision_Conductores":
                btnAgregar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnModificar.setEnabled(true); // Para asignar chofer al camión
                // Bloqueamos datos técnicos del camión
                lblMatricula.setEditable(false);
                lblMarca.setEditable(false);
                lblModelo.setEditable(false);
                lblKM.setEditable(false);
                ComboBoxMantenimiento.setEnabled(false);
                break;

            case "Revision_Mantenimiento":
                btnAgregar.setEnabled(false);
                btnEliminar.setEnabled(false);
                btnModificar.setEnabled(true); // Para cambiar estado de mantenimiento
                // Bloqueamos todo lo que no sea mantenimiento
                lblMatricula.setEditable(false);
                lblMarca.setEditable(false);
                lblModelo.setEditable(false);
                lblNombreChofer.setEditable(false);
                break;
        }
    }
    
    
    private void actualizarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    // El controlador se encarga de pedir todo al DAO y llenar el modelo
    controlador.cargarTabla(modelo); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textModelo = new javax.swing.JLabel();
        textNombreChofer = new javax.swing.JLabel();
        textKM = new javax.swing.JLabel();
        textMantenimiento = new javax.swing.JLabel();
        lblNumeracion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JTextField();
        lblMarca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblModelo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        textNumeraciónCamion = new javax.swing.JLabel();
        lblNombreChofer = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        textMatricula = new javax.swing.JLabel();
        lblKM = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        textMarca = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnReflescar = new javax.swing.JButton();
        ComboBoxMantenimiento = new javax.swing.JComboBox<>();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textModelo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textModelo.setText("Modelo: ");

        textNombreChofer.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textNombreChofer.setText("Nombre Chofer:");

        textKM.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textKM.setText("KM:");

        textMantenimiento.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textMantenimiento.setText("Mantenimiento :");

        lblNumeracion.setForeground(new java.awt.Color(204, 204, 204));
        lblNumeracion.setText("Numeracion");

        jLabel2.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        jLabel2.setText("Controlador DE camiones");

        lblMatricula.setForeground(new java.awt.Color(204, 204, 204));
        lblMatricula.setText("Matricula");

        lblMarca.setForeground(new java.awt.Color(204, 204, 204));
        lblMarca.setText("Marca");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Camione", "Matricula", "Marca", "Modelo", "Nom.Chofer", "Kilometros", "Matenimiento"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(600, 400));
        jTable1.setRequestFocusEnabled(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("N° Camione");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Matricula");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Marca");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Modelo");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Nom.Chofer");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Kilometros");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Matenimiento");
        }

        lblModelo.setForeground(new java.awt.Color(204, 204, 204));
        lblModelo.setText("Modelo");
        lblModelo.setPreferredSize(new java.awt.Dimension(64, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        textNumeraciónCamion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textNumeraciónCamion.setText("Numeración camion: ");

        lblNombreChofer.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreChofer.setText("Nombre del Chofer");
        lblNombreChofer.setPreferredSize(new java.awt.Dimension(117, 30));

        btnAgregar.setBackground(new java.awt.Color(102, 255, 102));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        textMatricula.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textMatricula.setText("Matricula: ");

        lblKM.setForeground(new java.awt.Color(204, 204, 204));
        lblKM.setText("Kilometros");

        btnModificar.setBackground(new java.awt.Color(51, 153, 255));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        textMarca.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textMarca.setText("Marca:");

        btnBuscar.setBackground(new java.awt.Color(153, 153, 153));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnReflescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReflescar.setText("Reflescar ");
        btnReflescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReflescarActionPerformed(evt);
            }
        });

        ComboBoxMantenimiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preventivo", "Correctivo" }));
        ComboBoxMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxMantenimientoActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExit.setText("Volver");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textKM)
                                    .addComponent(textMantenimiento)
                                    .addComponent(textNombreChofer)
                                    .addComponent(textModelo)
                                    .addComponent(textMarca)
                                    .addComponent(textMatricula)
                                    .addComponent(textNumeraciónCamion))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNumeracion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombreChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblKM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ComboBoxMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReflescar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReflescar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNumeraciónCamion)
                            .addComponent(lblNumeracion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMatricula))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMarca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textModelo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombreChofer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblKM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textKM))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBoxMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMantenimiento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar)
                            .addComponent(btnBuscar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int filaSeleccionada = jTable1.getSelectedRow();
    
    if (filaSeleccionada >= 0) {
        // Obtenemos el ID de la primera columna (columna 0)
        String id = jTable1.getValueAt(filaSeleccionada, 0).toString();
        
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres eliminar el camión ID: " + id + "?");
        
        if (confirmar == JOptionPane.YES_OPTION) {
            if (controlador.borrar(id)) {
                JOptionPane.showMessageDialog(this, "Registro eliminado de la base de datos");
                actualizarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Primero selecciona un camión de la tabla.");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    String patente = lblMatricula.getText();
    String marca = lblMarca.getText();
    String modelo = lblModelo.getText();
    String anio = "2024"; 
    String km = lblKM.getText();
    String tipoMantenimiento = ComboBoxMantenimiento.getSelectedItem().toString();
    
    // Ahora el controlador recibirá los 6 parámetros correctamente
    if (controlador.registrar(patente, marca, modelo, anio, km, tipoMantenimiento)) {
        JOptionPane.showMessageDialog(this, "¡Registro guardado!");
        actualizarTabla();
    } else {
        JOptionPane.showMessageDialog(this, "Error al guardar.");
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    String id = lblNumeracion.getText(); 
        String patente = lblMatricula.getText();
        String marca = lblMarca.getText();
        String modelo = lblModelo.getText();
        String anio = "2024"; 
        String km = lblKM.getText();
        
        // Capturamos el ComboBox
        String tipoMantenimiento = ComboBoxMantenimiento.getSelectedItem().toString();

        // Añadimos tipoMantenimiento al final
        if (controlador.editar(id, patente, marca, modelo, anio, km, tipoMantenimiento)) {
            JOptionPane.showMessageDialog(this, "Datos actualizados correctamente");
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo modificar el registro.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    // 1. Añadimos "tipo_mantenimiento" a las opciones
        String[] opciones = {"patente", "marca", "modelo", "id_conductor", "tipo_mantenimiento"};
        
        // 2. Pedir al usuario que elija una categoría
        String campo = (String) JOptionPane.showInputDialog(this, 
                "Seleccione el criterio de búsqueda:", "Buscar Camión",
                JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        
        if (campo != null) {
            // 3. Pedir el valor a buscar
            String valor = JOptionPane.showInputDialog(this, "Ingrese el valor de " + campo + ":");
            
            if (valor != null && !valor.trim().isEmpty()) {
                DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                controlador.buscarEnTabla(modelo, campo, valor);
                
                if (modelo.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
                    actualizarTabla(); 
                }
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReflescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReflescarActionPerformed
    // 1. Actualizamos la tabla de forma rápida y silenciosa
        actualizarTabla(); 
        
        // 2. Limpiamos los campos de texto y restauramos sus placeholders (color gris)
        lblNumeracion.setText("Numeracion");
        lblNumeracion.setForeground(new java.awt.Color(204, 204, 204));
        
        lblMatricula.setText("Matricula");
        lblMatricula.setForeground(new java.awt.Color(204, 204, 204));
        
        lblMarca.setText("Marca");
        lblMarca.setForeground(new java.awt.Color(204, 204, 204));
        
        lblModelo.setText("Modelo");
        lblModelo.setForeground(new java.awt.Color(204, 204, 204));
        
        lblNombreChofer.setText("Nombre del Chofer");
        lblNombreChofer.setForeground(new java.awt.Color(204, 204, 204));
        
        lblKM.setText("Kilometros");
        lblKM.setForeground(new java.awt.Color(204, 204, 204));
        
        // 3. Reiniciamos el ComboBox a su primera opción por defecto
        ComboBoxMantenimiento.setSelectedIndex(0);
    }//GEN-LAST:event_btnReflescarActionPerformed

    private void ComboBoxMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxMantenimientoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    // 1. Obtenemos el índice de la fila que el usuario seleccionó
        int fila = jTable1.getSelectedRow();
        
        // 2. Verificamos que realmente haya seleccionado una fila válida
        if (fila >= 0) {
            // 3. Pasamos los datos de la tabla a las cajas de texto (las columnas empiezan en 0)
            
            lblNumeracion.setText(jTable1.getValueAt(fila, 0).toString());
            lblNumeracion.setForeground(java.awt.Color.BLACK); // Pasamos a letra negra para quitar el efecto "Guia"
            
            lblMatricula.setText(jTable1.getValueAt(fila, 1).toString());
            lblMatricula.setForeground(java.awt.Color.BLACK);
            
            lblMarca.setText(jTable1.getValueAt(fila, 2).toString());
            lblMarca.setForeground(java.awt.Color.BLACK);
            
            lblModelo.setText(jTable1.getValueAt(fila, 3).toString());
            lblModelo.setForeground(java.awt.Color.BLACK);
            
            lblNombreChofer.setText(jTable1.getValueAt(fila, 4).toString());
            lblNombreChofer.setForeground(java.awt.Color.BLACK);
            
            lblKM.setText(jTable1.getValueAt(fila, 5).toString());
            lblKM.setForeground(java.awt.Color.BLACK);
            
            // 4. Para el ComboBox, tomamos el String de la columna 6 y le decimos que lo seleccione
            String mantenimiento = jTable1.getValueAt(fila, 6).toString();
            ComboBoxMantenimiento.setSelectedItem(mantenimiento);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
    Menu ventanaMenu = new Menu(usuarioActual);
    ventanaMenu.setVisible(true);
    ventanaMenu.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(ControlesCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlesCamiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxMantenimiento;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReflescar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lblKM;
    private javax.swing.JTextField lblMarca;
    private javax.swing.JTextField lblMatricula;
    private javax.swing.JTextField lblModelo;
    private javax.swing.JTextField lblNombreChofer;
    private javax.swing.JTextField lblNumeracion;
    private javax.swing.JLabel textKM;
    private javax.swing.JLabel textMantenimiento;
    private javax.swing.JLabel textMarca;
    private javax.swing.JLabel textMatricula;
    private javax.swing.JLabel textModelo;
    private javax.swing.JLabel textNombreChofer;
    private javax.swing.JLabel textNumeraciónCamion;
    // End of variables declaration//GEN-END:variables
}
