/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Controle.AsignacionControlador; 
import Modelo.Usuarios;
import java.awt.Color;

public class ControlesAsignacion extends javax.swing.JFrame {

    private DefaultTableModel modelo;
    private Usuarios usuarioActual;
    // Usamos el nombre de tu controlador externo
    private AsignacionControlador controladorAsig = new AsignacionControlador();

   public ControlesAsignacion(Usuarios usuario) {
    this.usuarioActual = usuario; // Guardamos quien entró
    initComponents();
    this.setLocationRelativeTo(null);
    configurarTabla();
    refrescarTodo(); 
    aplicarPermisos(); // <--- ESTO ACTIVA EL BLOQUEO DE BOTONES
    }

    private void aplicarPermisos() {
    if (usuarioActual == null) return;
    
    String rol = usuarioActual.getRol();

    // Si el rol es de revisión, bloqueamos los controles
    if (rol.equalsIgnoreCase("Revision_Conductores") || rol.equalsIgnoreCase("Revision_Mantenimiento")) {
        btnAsignar.setEnabled(false); 
        ComboBoxConductor.setEnabled(false);
        ComboBoxCamion.setEnabled(false);
        
        // Feedback visual en el título
        this.setTitle("Asignaciones - MODO CONSULTA (Solo Lectura)");
    }
    }

                                            

    private void configurarTabla() {
        modelo = new DefaultTableModel(
            new Object [][] {},
            new String [] { "Conductor", "Patente del Camion" }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Bloquea edición directa en celdas
            }
        };
        jTableAsignacion.setModel(modelo);
    }

    private void refrescarTodo() {
        try {
            controladorAsig.cargarCombos(ComboBoxCamion, ComboBoxConductor);
            controladorAsig.actualizarTabla(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
        }    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBoxConductor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxCamion = new javax.swing.JComboBox<>();
        btnAsignar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAsignacion = new javax.swing.JTable();
        btnReflescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboBoxConductor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxConductorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Stencil", 2, 36)); // NOI18N
        jLabel2.setText("Controlador DE Asignacion");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Conductor:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Camion:");

        ComboBoxCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCamionActionPerformed(evt);
            }
        });

        btnAsignar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jTableAsignacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Conductor", "Patente del Camion"
            }
        ));
        jTableAsignacion.setPreferredSize(new java.awt.Dimension(600, 400));
        jTableAsignacion.setRequestFocusEnabled(false);
        jTableAsignacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAsignacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAsignacion);

        btnReflescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReflescar.setText("Reflescar ");
        btnReflescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReflescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReflescar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(btnAsignar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnReflescar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxCamion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btnAsignar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxConductorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxConductorActionPerformed

    private void ComboBoxCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCamionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCamionActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    Menu ventanaMenu = new Menu(usuarioActual); 
        ventanaMenu.setVisible(true);
        ventanaMenu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jTableAsignacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAsignacionMouseClicked

    }//GEN-LAST:event_jTableAsignacionMouseClicked

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
    if (usuarioActual == null) return;

    String patente = ComboBoxCamion.getSelectedItem().toString();
    String chofer = ComboBoxConductor.getSelectedItem().toString();

    // Chamada corrixida co nome exacto do método do controlador
    boolean exito = controladorAsig.realizarAsignacionSegura(patente, chofer, usuarioActual);

    if (exito) {
        JOptionPane.showMessageDialog(this, "Asignación gardada con éxito.");
        refrescarTodo();
    } else {
        JOptionPane.showMessageDialog(this, "Erro: Non tes permisos ou o camión xa está ocupado.");
    }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnReflescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReflescarActionPerformed
    refrescarTodo();
        JOptionPane.showMessageDialog(this, "Datos actualizados.");
    }//GEN-LAST:event_btnReflescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            Modelo.Usuarios usuarioPrueba = new Modelo.Usuarios();
            
            // Corrixido: Usar setUsername en lugar de setUsuario
            usuarioPrueba.setUsername("TestAdmin"); 
            usuarioPrueba.setRol("Revision_Conductores"); 
            
            new ControlesAsignacion(usuarioPrueba).setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCamion;
    private javax.swing.JComboBox<String> ComboBoxConductor;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnReflescar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAsignacion;
    // End of variables declaration//GEN-END:variables
}
