/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controle.ChoferControlador;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import Modelo.Usuarios;


public class ControlesChoferes extends javax.swing.JFrame {

    ChoferControlador controlador = new ChoferControlador();
    private Usuarios usuarioActual;

    public ControlesChoferes() {
        initComponents();
        prepararVista();
    }

    public ControlesChoferes(Usuarios usuario) {
        this.usuarioActual = usuario;
        initComponents();
        prepararVista();
        actualizarTabla();
        configurarPlaceholders();
        aplicarPermisos(); 
    }

    private void prepararVista() {
        GestorVistas.configurarVentanaBase(this, "Gestión de Choferes - Hirata");
        // Enter para agregar, Escape para volver al menú
        GestorVistas.configurarAtajosGlobales(this, btnAgregar, false); 
        GestorVistas.configurarTabla(tablaChoferes);
    }

    public void aplicarPermisos() {
        if (usuarioActual == null) return;
        String rol = usuarioActual.getRol();

        if (!rol.equals("Admin")) {
            btnAgregar.setEnabled(false);
            btnEliminar.setEnabled(false);
            btnModificar.setEnabled(false);
            
            lblRut.setEditable(false);
            lblNombre.setEditable(false);
            lblApellidos.setEditable(false);
            lblLicencia.setEditable(false);
            lblTelefono.setEditable(false);
            
            if (rol.equals("Revision_Mantenimiento") || rol.equals("Revision_Conductores")) {
                setTitle("Consulta de Choferes - Modo Lectura");
            }
        }
    }

    private void actualizarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaChoferes.getModel();
        controlador.cargarTabla(modelo); 
    }

    private void configurarPlaceholders() {
        javax.swing.JTextField[] campos = {lblRut, lblNombre, lblApellidos, lblLicencia, lblTelefono};
        for (javax.swing.JTextField campo : campos) {
            String textoGuia = campo.getText();
            campo.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    if (campo.getText().equals(textoGuia)) {
                        campo.setText("");
                        campo.setForeground(Color.BLACK);
                    }
                }
                @Override
                public void focusLost(FocusEvent e) {
                    if (campo.getText().isEmpty()) {
                        campo.setForeground(new Color(204, 204, 204));
                        campo.setText(textoGuia);
                    }
                }
            });
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReflescar = new javax.swing.JButton();
        lblLicencia = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        textNumeraciónCamion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        textMatricula = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        textModelo = new javax.swing.JLabel();
        textNombreChofer = new javax.swing.JLabel();
        lblRut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JTextField();
        textMarca = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaChoferes = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnReflescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReflescar.setText("Reflescar ");
        btnReflescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReflescarActionPerformed(evt);
            }
        });

        lblLicencia.setForeground(new java.awt.Color(204, 204, 204));
        lblLicencia.setText("Licencia");
        lblLicencia.setPreferredSize(new java.awt.Dimension(64, 30));

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        textNumeraciónCamion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textNumeraciónCamion.setText("Rut: ");

        lblTelefono.setForeground(new java.awt.Color(204, 204, 204));
        lblTelefono.setText("Telefono");
        lblTelefono.setPreferredSize(new java.awt.Dimension(117, 30));

        btnAgregar.setBackground(new java.awt.Color(102, 255, 102));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        textMatricula.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textMatricula.setText("Nombre: ");

        btnModificar.setBackground(new java.awt.Color(51, 153, 255));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        textModelo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textModelo.setText("lblLicencia: ");

        textNombreChofer.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textNombreChofer.setText("Telefono");

        lblRut.setForeground(new java.awt.Color(204, 204, 204));
        lblRut.setText("Rut");
        lblRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblRutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Stencil", 2, 24)); // NOI18N
        jLabel2.setText("Controlador DE Choferes");

        lblNombre.setForeground(new java.awt.Color(204, 204, 204));
        lblNombre.setText("Nombre");

        lblApellidos.setForeground(new java.awt.Color(204, 204, 204));
        lblApellidos.setText("Apellidos");

        textMarca.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textMarca.setText("Apellidos:");

        tablaChoferes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rut", "Nombre", "Apellidos", "Licencia", "Telefono"
            }
        ));
        tablaChoferes.setPreferredSize(new java.awt.Dimension(600, 400));
        tablaChoferes.setRequestFocusEnabled(false);
        tablaChoferes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaChoferesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaChoferes);

        btnBuscar.setBackground(new java.awt.Color(153, 153, 153));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textNombreChofer)
                                    .addComponent(textModelo)
                                    .addComponent(textMarca)
                                    .addComponent(textMatricula)
                                    .addComponent(textNumeraciónCamion))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRut, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregar)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(136, 136, 136)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReflescar)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnReflescar)
                    .addComponent(btnVolver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNumeraciónCamion)
                            .addComponent(lblRut, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMatricula))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textMarca))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textModelo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNombreChofer))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar)
                            .addComponent(btnBuscar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReflescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReflescarActionPerformed
        GestorVistas.limpiarCampos(this.getContentPane());
        // Restauramos los textos de guía
        lblRut.setText("Rut");
        lblNombre.setText("Nombre");
        lblApellidos.setText("Apellidos");
        lblLicencia.setText("Licencia");
        lblTelefono.setText("Telefono");
        actualizarTabla();
    }//GEN-LAST:event_btnReflescarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablaChoferes.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String rut = tablaChoferes.getValueAt(filaSeleccionada, 0).toString();
            int confirmar = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres eliminar al chofer RUT: " + rut + "?");
            
            if (confirmar == JOptionPane.YES_OPTION) {
                // AQUÍ QUITAMOS LOS COMENTARIOS
                if (controlador.borrar(rut)) {
                    JOptionPane.showMessageDialog(this, "Chofer eliminado.");
                    actualizarTabla();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al eliminar.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Primero selecciona un chofer de la tabla.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String rut = lblRut.getText();
        String nombre = lblNombre.getText();
        String apellidos = lblApellidos.getText();
        String licencia = lblLicencia.getText();
        String telefono = lblTelefono.getText();
        
        // AQUÍ QUITAMOS LOS COMENTARIOS
        if (controlador.registrar(rut, nombre, apellidos, licencia, telefono)) {
            JOptionPane.showMessageDialog(this, "¡Chofer guardado!");
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // Capturamos los datos exactos de los campos de texto del chofer
        String rut = lblRut.getText();
        String nombre = lblNombre.getText();
        String apellidos = lblApellidos.getText();
        String licencia = lblLicencia.getText();
        String telefono = lblTelefono.getText();

        // Llamamos al método editar del ChoferControlador
        if (controlador.editar(rut, nombre, apellidos, licencia, telefono)) {
            JOptionPane.showMessageDialog(this, "Datos actualizados correctamente");
            actualizarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo modificar el registro.");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tablaChoferesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaChoferesMouseClicked
        int fila = tablaChoferes.getSelectedRow();
        
        if (fila >= 0) {
            // Columna 0: RUT
            lblRut.setText(tablaChoferes.getValueAt(fila, 0).toString());
            lblRut.setForeground(java.awt.Color.BLACK);
            
            // Columna 1: Nombre
            lblNombre.setText(tablaChoferes.getValueAt(fila, 1).toString());
            lblNombre.setForeground(java.awt.Color.BLACK);
            
            // Columna 2: Apellidos
            lblApellidos.setText(tablaChoferes.getValueAt(fila, 2).toString());
            lblApellidos.setForeground(java.awt.Color.BLACK);
            
            // Columna 3: Licencia
            lblLicencia.setText(tablaChoferes.getValueAt(fila, 3).toString());
            lblLicencia.setForeground(java.awt.Color.BLACK);
            
            // Columna 4: Teléfono
            lblTelefono.setText(tablaChoferes.getValueAt(fila, 4).toString());
            lblTelefono.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_tablaChoferesMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // 1. Cambiamos las opciones por los atributos reales de los choferes
        String[] opciones = {"rut", "nombre", "licencia", "telefono"};

        // 2. Corregimos el título de la ventana a "Buscar Chofer"
        String campo = (String) JOptionPane.showInputDialog(this, 
            "Seleccione el criterio de búsqueda:", "Buscar Chofer",
            JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        if (campo != null) {
            // 3. Pedir el valor a buscar
            String valor = JOptionPane.showInputDialog(this, "Ingrese el valor de " + campo + ":");

            if (valor != null && !valor.trim().isEmpty()) {
                // Aquí usamos la tabla correcta de choferes
                DefaultTableModel modelo = (DefaultTableModel) tablaChoferes.getModel();
                
                // IMPORTANTE: Asegúrate de que el 'controlador' que estás usando aquí 
                // sea la instancia de 'ChoferControlador'.
                controlador.buscarEnTabla(modelo, campo, valor);

                if (modelo.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
                    actualizarTabla();
                }
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void lblRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRutActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    Menu ventanaMenu = new Menu(usuarioActual);
    ventanaMenu.setVisible(true);
    ventanaMenu.setLocationRelativeTo(null);
    this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlesChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlesChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlesChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlesChoferes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlesChoferes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReflescar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblApellidos;
    private javax.swing.JTextField lblLicencia;
    private javax.swing.JTextField lblNombre;
    private javax.swing.JTextField lblRut;
    private javax.swing.JTextField lblTelefono;
    private javax.swing.JTable tablaChoferes;
    private javax.swing.JLabel textMarca;
    private javax.swing.JLabel textMatricula;
    private javax.swing.JLabel textModelo;
    private javax.swing.JLabel textNombreChofer;
    private javax.swing.JLabel textNumeraciónCamion;
    // End of variables declaration//GEN-END:variables
}