/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controle.CamionControlador;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
/**
 *
 * @author tomas
 */
public class ControlesCamiones extends javax.swing.JFrame {

    // 1. Instanciamos el controlador
    CamionControlador controlador = new CamionControlador();

    public ControlesCamiones() {
        initComponents();
        // 2. Cargamos los datos en la tabla
        actualizarTabla();
        // 3. Activamos el efecto para que se borren al escribir
        configurarPlaceholders();
    }

    // --- MÉTODO MAGICO PARA LOS EDIT TEXT ---
    private void configurarPlaceholders() {
        // Metemos todos tus campos en una lista para no repetir codigo
        javax.swing.JTextField[] campos = {
            lblNumeracion, lblMatricula, lblMarca, lblModelo, 
            lblNombreChofer, lblKM, lblMantenimiento
        };

        for (javax.swing.JTextField campo : campos) {
            // Guardamos el nombre original que pusiste en NetBeans como "guia"
            String textoGuia = campo.getText();

            campo.addFocusListener(new FocusAdapter() {
                @Override
                public void focusGained(FocusEvent e) {
                    // Si el usuario hace clic y está el texto de guia, lo borramos
                    if (campo.getText().equals(textoGuia)) {
                        campo.setText("");
                        campo.setForeground(Color.BLACK); // Color de letra normal al escribir
                    }
                }

                @Override
                public void focusLost(FocusEvent e) {
                    // Si el usuario se sale y no escribió nada, ponemos la guia de nuevo
                    if (campo.getText().isEmpty()) {
                        campo.setForeground(new Color(204, 204, 204)); // Color gris
                        campo.setText(textoGuia);
                    }
                }
            });
        }
    }

    private void actualizarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        controlador.cargarTabla(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textModelo = new javax.swing.JLabel();
        textNombreChofer = new javax.swing.JLabel();
        textKM = new javax.swing.JLabel();
        textMantenimiento = new javax.swing.JLabel();
        lblNumeracion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JTextField();
        lblMarca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblModelo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        textNumeraciónCamion = new javax.swing.JLabel();
        lblNombreChofer = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        textMatricula = new javax.swing.JLabel();
        lblKM = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        textMarca = new javax.swing.JLabel();
        lblMantenimiento = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnReflescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textModelo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textModelo.setText("Modelo: ");

        textNombreChofer.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textNombreChofer.setText("Nombre Chofer:");

        textKM.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textKM.setText("KM:");

        textMantenimiento.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textMantenimiento.setText("Mantenimiento (BOOL):");

        lblNumeracion.setForeground(new java.awt.Color(204, 204, 204));
        lblNumeracion.setText("Numeracion");

        jLabel2.setFont(new java.awt.Font("Stencil", 2, 24)); // NOI18N
        jLabel2.setText("Controlador DE camiones");

        lblMatricula.setForeground(new java.awt.Color(204, 204, 204));
        lblMatricula.setText("Matricula");

        lblMarca.setForeground(new java.awt.Color(204, 204, 204));
        lblMarca.setText("Marca");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Camione", "Matricula", "Marca", "Modelo", "Nom.Chofer", "Kilometros", "Matenimiento"
            }
        ));
        jTable1.setPreferredSize(new java.awt.Dimension(500, 80));
        jTable1.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        lblModelo.setForeground(new java.awt.Color(204, 204, 204));
        lblModelo.setText("Modelo");

        btnEliminar.setBackground(new java.awt.Color(255, 0, 51));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        textNumeraciónCamion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textNumeraciónCamion.setText("Numeración camion: ");

        lblNombreChofer.setForeground(new java.awt.Color(204, 204, 204));
        lblNombreChofer.setText("Nombre del Chofer");

        btnAgregar.setBackground(new java.awt.Color(102, 255, 102));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        textMatricula.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textMatricula.setText("Matricula: ");

        lblKM.setForeground(new java.awt.Color(204, 204, 204));
        lblKM.setText("Kilometros");

        btnModificar.setBackground(new java.awt.Color(51, 153, 255));
        btnModificar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        textMarca.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        textMarca.setText("Marca:");

        lblMantenimiento.setForeground(new java.awt.Color(204, 204, 204));
        lblMantenimiento.setText("Mantenimiento");

        btnBuscar.setBackground(new java.awt.Color(153, 153, 153));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnReflescar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReflescar.setText("Reflescar ");
        btnReflescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReflescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textMantenimiento)
                                    .addComponent(textKM)
                                    .addComponent(textNombreChofer)
                                    .addComponent(textMarca)
                                    .addComponent(textMatricula)
                                    .addComponent(textNumeraciónCamion)
                                    .addComponent(textModelo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeracion)
                                    .addComponent(lblMatricula)
                                    .addComponent(lblMarca)
                                    .addComponent(lblModelo)
                                    .addComponent(lblNombreChofer)
                                    .addComponent(lblKM)
                                    .addComponent(lblMantenimiento, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAgregar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReflescar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnReflescar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNumeraciónCamion)
                            .addComponent(lblNumeracion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textMatricula)
                            .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textMarca)
                            .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textModelo)
                            .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNombreChofer)
                            .addComponent(lblNombreChofer, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textKM)
                            .addComponent(lblKM, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textMantenimiento)
                            .addComponent(lblMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar)
                            .addComponent(btnBuscar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    int filaSeleccionada = jTable1.getSelectedRow();
    
    if (filaSeleccionada >= 0) {
        // Obtenemos el ID de la primera columna (columna 0)
        String id = jTable1.getValueAt(filaSeleccionada, 0).toString();
        
        int confirmar = JOptionPane.showConfirmDialog(this, "¿Seguro que quieres eliminar el camión ID: " + id + "?");
        
        if (confirmar == JOptionPane.YES_OPTION) {
            if (controlador.borrar(id)) {
                JOptionPane.showMessageDialog(this, "Registro eliminado de la base de datos");
                actualizarTabla();
            } else {
                JOptionPane.showMessageDialog(this, "Error al eliminar.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Primero selecciona un camión de la tabla.");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    // Capturar datos de la vista
    String patente = lblMatricula.getText();
    String marca = lblMarca.getText();
    String modelo = lblModelo.getText();
    String anio = "2024"; // Puedes cambiar esto por un campo de texto si lo tienes
    String km = lblKM.getText();

    // El controlador llama al DAO internamente
    if (controlador.registrar(patente, marca, modelo, anio, km)) {
        JOptionPane.showMessageDialog(this, "¡Camión guardado en la base de datos!");
        actualizarTabla(); // Refresca la tabla automáticamente
    } else {
        JOptionPane.showMessageDialog(this, "Error al guardar. Revisa la conexión.");
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    String id = lblNumeracion.getText(); 
    String patente = lblMatricula.getText();
    String marca = lblMarca.getText();
    String modelo = lblModelo.getText();
    String anio = "2024"; 
    String km = lblKM.getText();

    if (controlador.editar(id, patente, marca, modelo, anio, km)) {
        JOptionPane.showMessageDialog(this, "Datos actualizados correctamente");
        actualizarTabla();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo modificar el registro.");
    }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    // 1. Opciones de búsqueda
    String[] opciones = {"patente", "marca", "modelo", "id_conductor"};
    
    // 2. Pedir al usuario que elija una categoría
    String campo = (String) JOptionPane.showInputDialog(this, 
            "Seleccione el criterio de búsqueda:", "Buscar Camión",
            JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
    
    if (campo != null) {
        // 3. Pedir el valor a buscar
        String valor = JOptionPane.showInputDialog(this, "Ingrese el valor de " + campo + ":");
        
        if (valor != null && !valor.trim().isEmpty()) {
            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            controlador.buscarEnTabla(modelo, campo, valor);
            
            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No se encontraron resultados.");
                actualizarTabla(); // Si no hay nada, volvemos a mostrar todo
            }
        }
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnReflescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReflescarActionPerformed
    actualizarTabla(); // Recarga todos los datos de la DB
    JOptionPane.showMessageDialog(this, "Tabla actualizada");
    }//GEN-LAST:event_btnReflescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(ControlesCamiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlesCamiones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnReflescar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lblKM;
    private javax.swing.JTextField lblMantenimiento;
    private javax.swing.JTextField lblMarca;
    private javax.swing.JTextField lblMatricula;
    private javax.swing.JTextField lblModelo;
    private javax.swing.JTextField lblNombreChofer;
    private javax.swing.JTextField lblNumeracion;
    private javax.swing.JLabel textKM;
    private javax.swing.JLabel textMantenimiento;
    private javax.swing.JLabel textMarca;
    private javax.swing.JLabel textMatricula;
    private javax.swing.JLabel textModelo;
    private javax.swing.JLabel textNombreChofer;
    private javax.swing.JLabel textNumeraciónCamion;
    // End of variables declaration//GEN-END:variables
}
