/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Usuarios;

public class Menu extends javax.swing.JFrame {

    private Usuarios usuarioLogueado;

    // Constructor principal que recibe la sesión
    public Menu(Usuarios usuario) {
        this.usuarioLogueado = usuario; 
        initComponents();
        this.setLocationRelativeTo(null);
        // Opcional: Podrías poner un JLabel que diga "Bienvenido: " + usuario.getNombre();
    }
    
    // Constructor vacío por si necesitas previsualizar en el diseño
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCamiones = new javax.swing.JButton();
        btnChoferes = new javax.swing.JButton();
        btnAsignacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("MENU");

        btnCamiones.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnCamiones.setText("Camiones");
        btnCamiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCamionesActionPerformed(evt);
            }
        });

        btnChoferes.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnChoferes.setText("Choferes");
        btnChoferes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoferesActionPerformed(evt);
            }
        });

        btnAsignacion.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        btnAsignacion.setText("Asignacion");
        btnAsignacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAsignacion)
                    .addComponent(btnChoferes)
                    .addComponent(jLabel1)
                    .addComponent(btnCamiones))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(btnCamiones, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChoferes, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCamionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCamionesActionPerformed
    ControlesCamiones v = new ControlesCamiones(this.usuarioLogueado);
        v.setVisible(true);
        this.dispose(); // Cerramos el menú al entrar a una gestión
    }//GEN-LAST:event_btnCamionesActionPerformed

    private void btnChoferesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoferesActionPerformed
    ControlesChoferes v = new ControlesChoferes(this.usuarioLogueado);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnChoferesActionPerformed

    private void btnAsignacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignacionActionPerformed
    ControlesAsignacion v = new ControlesAsignacion(this.usuarioLogueado);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAsignacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignacion;
    private javax.swing.JButton btnCamiones;
    private javax.swing.JButton btnChoferes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
